INSERT INTO devour (food, devoured) VALUES ("STEAK", true);
INSERT INTO devour (food, devoured) VALUES ("RAMEN", true);
INSERT INTO devour (food, devoured) VALUES ("RICE", true);
INSERT INTO devour (food, devoured) VALUES ("BULGOGI", true);
INSERT INTO devour (food, devoured) VALUES ("POKE BOWL", true);
INSERT INTO devour (food, devoured) VALUES ("SUSHI", false);
INSERT INTO devour (food, devoured) VALUES ("BOTTLE OF RED WINE", false);
INSERT INTO devour (food, devoured) VALUES ("CURRY", false);
INSERT INTO devour (food, devoured) VALUES ("OATMEAL", false);
INSERT INTO devour (food, devoured) VALUES ("PORK CHOP", false);